apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: red
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: red
    spec:
      containers:
      - name: red
        image: segment/red:v0.3.0
        args: [
            "proxy",
            "-upstream", "consul://consul.default.svc.cluster.local:8500/redis?cluster=dev",
            "-dogstatsd", "datadog-agent-datadog:8125"
        ]
        ports:
        - containerPort: 6379
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: red
  labels:
    name: red
spec:
  clusterIP: None
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
  selector:
    app: red

---

apiVersion: batch/v1
kind: Job
metadata:
  name: red-test
spec:
  parallelism: 1
  template:
    metadata:
      name: red-test
    spec:
      containers:
        - name: red-test
          image: segment/red:latest
          args: [
              "test",
              "-proxy", "red:6479",
              "-dogstatsd", "datadog-agent-datadog:8125",
              "-runs", "100"
          ]
      restartPolicy: Never
